DROP TABLE asistencia;
CREATE TABLE asistencia (nombre varchar(50),apellidos varchar(50), telefono varchar(50), correo varchar(100), genero varchar(10),asistenciaID INT);

 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (34,'Lupita','Rodriguez','5242889','anaRod99@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (1,'Maria','Duarte Ruiz','5247899','mari77@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (2,'Laura','Diaz Ordaz','5291233','lauDiz@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (3,'Karina','Scarlet Ordaz','5247593','skarin99@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (4,'Tara','Gomez Soliz','5289009','taraMez@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (5,'Roberto','Gutierrez Solano','5275460','robetSol90@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (6,'Josue','Casillas Capis','5212332','JosCp12@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (7,'Francisco','Lopez Capis','5295578','FranLop98@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (8,'Ricardo','Galvan Duran','5228839','RicDur98@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (9,'Jose','Medina Talavera','5298477','joshTal93@ejemplo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (10,'Celerina ','Mendez Aguilar','7861237058','Cele_MendezA@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (11,'Brenda Guadalupe ','Escutia Ruiz','4471082287','onebren.BrendaEscutia@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (12,'Jessica Noemí ','Cervantes García','7861188248','jessy.cervantes94@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (13,'Karina Yareli ','Hernández Alonso','4432194220','yareli_1201@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (14,'Angeles Yuliana ','Lopez Maldonado','4251340161','yulianalopezmaldonado05@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (15,'Guadalupe Karina','De La Torre Tovar','4431209789','cari-8@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (16,'Celerina ','Mendez Aguilar','7861237058',' Cele_mendeza@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (17,'Kathia Guadalupe ','Ruiz Toral','7861237058','kathiaruito@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (18,'Monserrath ','Frias Zetina','4521444432','Montsefrias12@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (19,'Estephanie ','Celedón Martinez','4431710008','estephaniecm10@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (20,'Fernando Jose ','Cervantes Carranza','3541149986','Fernandojose030599@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (21,'Cecilia ','Gonzalez Mata','4521076300','angeles.pereyra@outlook.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (22,'Edgar Octavio ','Rodriguez Garcia','4191055481','octavo100.eorg@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (23,'Daniela Guadalupe ','García Martínez','7861275925','daniyelagarciia@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (24,'Laura ','Arreola Carrillo','4471218665','arreola0499@gmail.com ','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (25,'Daniela Jazmin ','Muñoz Correa','4251216803','Hannajaz@yahoo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (26,'Betsy Yicel ','Ruiz Velázquez','4433868295','yicelvelazquez01@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (27,'Carlos Rene ','Figueroa Manriquez','4432307452','Carlosrenecobaem@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (28,'Aura Yesenia ','Tadeo Bucio','4531316957','aura_bucio_19@hotmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (29,'Maria Fernanda','Macia Gacias','4521159217','Patii67@hotmail.com ','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (30,'Muñoz Correa ','Daniela Jazmin','3531016325','hannajaz@yahoo.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (31,'Elisa Ireri ','Cárdenas Raya','4433868295','Elisacardenas3829@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (32,'Jhoana Lizbeth ','Gutierrez Gutierrez','4433771201','lizbethgut8@gmail.com','femenino');
 INSERT INTO asistencia (asistenciaID,nombre, apellidos, telefono, correo, genero) VALUES (33,'Daniela','Duarte Lemos','4435340205','Daniela323.dcr@gmail.com','femenino');
